[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Vincent Serpoul <vincent@serpoul.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "1-2"
harness = false